---
driver:
  name: docker
  use_sudo: false
  privileged: true
  provision_command: /usr/sbin/sshd -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid

platforms:
  - name: centos-7
    driver:
      run_command: /usr/sbin/init
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-16.04
    driver:
      run_command: /sbin/init

provisioner:
  name: ansible_playbook
  hosts: localhost
  role_name: contentwise.docker
  ansible_verbose: true
  idempotency_test: true

suites:
  - name: default