---
- name: install docker
  yum:
    name: "{{ docker_rpm_location }}"
  when: ansible_os_family == 'RedHat'

- block:
    - name: install prerequisites
      package:
        name: libseccomp2
    - name: install docker
      apt:
        deb: "{{ docker_deb_location }}"
  when: ansible_os_family == 'Debian'

- name: add users to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: True
  with_items: "{{ docker_users }}"
  when: docker_users

- name: ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes

- include_tasks: docker-compose.yml
  when: docker_install_compose
