---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: create configuration directory
  file:
    path: /etc/docker
    state: directory

# https://docs.docker.com/storage/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production
- name: configure direct lvm
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  when: docker_directlvm_device is defined
  notify: restart docker

- name: ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers
  when: docker_restart_on_package_change

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include_tasks: docker-users.yml
  when: docker_users
