---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: install docker
  yum:
    name: "{{ docker_rpm_location }}"
  notify: restart docker